### PR TITLE
Two bug fixes and added a config entry for default greeting

### LINKED ISSUE #3: Crashes when @doc is used without an argument.
When `@doc` is used with no parameters, clojurebot crashes and quits IRC.

```
2017-03-09 13:42:30	someuser	 @doc
2017-03-09 13:42:31	<--	lispbot (~lispbot@some-ip) has quit (Remote host closed the connection)
```

### PR DESCRIPTION
**Pull request by emanuelmd**
This should fix #3 and #4
I'm not entirely satisifed with "doc" command but it won't truncate and won't crash the bot for now.

### CODE REVIEW

File: src/clojurebot/core.clj [hunk 1]
```diff
@@ -85,12 +90,16 @@
 (reg-command
   "doc"
   (fn [sym-name]
-    (if sym-name
+    (if (not (empty? sym-name))
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: Why are you checking for empty? Its not supposed to be a collection, its a symbol. Right? In clojure if you want to check if a collection is empty you don't use `empty?` but instead `seq`

File: src/clojurebot/core.clj [hunk 2]
```diff
@@ -85,12 +90,16 @@
...
       (->> (symbol sym-name)
-           (resolve)
+           (resolve)                          
+           ;; TODO: If sym-name is not a valid symbol resolve returns nil
+           ;; find a way to skip the forms below and show an error like
+           ;; Error: symbol is not valid
            (meta)
-           (:doc))
-      (println "ERROR: No arguments provided"))))
+           (#(format "::: %s ::: \"%s\" " (:arglists %1) (:doc %1)))
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: This is considered bad practice. You don't do `(#(format))` inside of a `->>`

File: src/clojurebot/core.clj [hunk 3]
```diff
@@ -85,12 +90,16 @@
 (reg-command
   "doc"
   (fn [sym-name]
-    (if sym-name
+    (if (not (empty? sym-name))
       (->> (symbol sym-name)
-           (resolve)
+           (resolve)                          
+           ;; TODO: If sym-name is not a valid symbol resolve returns nil
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: You can do this by doing

```clojure
(if-let [sym (resolve (symbol sym-name))]
  (->> sym
       (meta)
       ...)
  (println "No docs for symbol:" sym-name))
```

File: src/clojurebot/core.clj [hunk 4]
```diff
@@ -41,6 +41,11 @@
   [name handler]
   (swap! commands assoc name handler))
 
+(defn replace-nl
+  "Replace occurences of \n from s with whitespace, so it doesn't trim the IRC output."
+  [s]
+  (clojure.string/replace s "\n " " "))
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: I'd use `(clojure.string/replace s #"\s+" " ")`, this way you're using a regex to replace ALL whitespace.

File: src/clojurebot/core.clj [hunk 5]
```diff
@@ -41,6 +41,11 @@
   [name handler]
   (swap! commands assoc name handler))
 
+(defn replace-nl
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: And perhaps also rename this one to `replace-ws` if you make the below change.

File: src/clojurebot/core.clj [hunk 6]
```diff
@@ -82,15 +91,27 @@
...
   (fn [sym-name]
-    (if sym-name
-      (->> (symbol sym-name)
-           (resolve)
-           (meta)
-           (:doc))
-      (println "ERROR: No arguments provided"))))
+    (if (not (clojure.string/blank? sym-name))
+        (->> (if-let [sym (symbol sym-name)]
+          (resolve)
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: You need to indent this to match the `(if-let ...)` form.

File: src/clojurebot/core.clj [hunk 7]
```diff
@@ -82,15 +91,27 @@
...
   "doc"
   (fn [sym-name]
-    (if sym-name
-      (->> (symbol sym-name)
-           (resolve)
-           (meta)
-           (:doc))
-      (println "ERROR: No arguments provided"))))
+    (if (not (clojure.string/blank? sym-name))
+        (->> (if-let [sym (symbol sym-name)]
```
Comment (kalouantonis) [inline src/clojurebot/core.clj]: This isn't correct. My comment said: 

```clojure
(if-let [sym (resolve (symbol sym-name))]
  (->> sym
       (meta)
       ...)
  (str "No docs for symbol: " sym-name))
```

Also, all forms in the `(->> ...)` should have the same indentation.

**Review by kalouantonis — COMMENTED** [review]
Have you tested that these changes work?

**Comment by kalouantonis** [comment]
Thanks for this. I'll be deploying the bot shortly.
